---
title: "Importance of being uncertain"
author: "Eric Leung "
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This vignette reviews the lessons learned in ["Points of Significance:
Importance of being uncertain"][uncertain].

[uncertain]: https://doi.org/10.1038/nmeth.2613

```{r Load Package}
library(poofsi)
```

Population distribution and its measures
========================================

```{r Population Distribution, fig.height=4, fig.width=5}
population_dist()
```

```{r Location and Spread, fig.height=7, fig.width=4}
location_plot()
```

Population parameters estimated by sampling
===========================================

Distribution of sample means from different distributions
=========================================================

Mean, standard deviation, and standard error of the mean
========================================================
